#+title: 洪久族: 纪念黄老师
#+OPTIONS: toc:nil ':t html-postamble:nil tags:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../minimal.css" />

文／[[http://hong.web.unc.edu/][洪久族]]

听说黄兆镇老师去世的消息已经一阵子了，这段时间五味杂陈，除了沉痛不舍，
还有不知如何面对和消化。大学时期已经离我越来越远，记忆也愈发模糊起来。
因为黄老师的离世，让我回温大学的一些点滴以及跟黄老师交往的一些回忆。

我本科在浙大上了黄老师开设的点集拓扑和代数拓扑课，除此之外还上了他组织
的一些讨论班，主题包括范畴学和代数几何。我大学第一学期原本在数学系，第
二学期进入竺可桢学院理科班。进入到理科班后，我对突然学习各种不同学科和
用英语教程非常不适应，有一年多时间有点迷失，而且那期间数学课程没有开设
很多。从大三开始专业分流，我又开始更集中学习数学课程。大三上学期，我上
了黄老师的点集拓扑，这门课当时在浙大是算是比较抽象和难学，可能主要还是
因为黄老师比较严厉和高要求吧。当时理科班里面我跟丛旭日比较近，经常一起
上课和参加讨论班。杨晓奎当时也是同学，当时理科班公认的数学最好的是三班
的朱孝天和二班的杨晓奎。比我低一级的孙晟昊也跟我们一起上课，我是一直把
孙晟昊当成同学的，因为后来我们还一起参加讨论班一起讨论代数几何。也因为
讨论班的关系，我跟低一级的杨田，谢知章，石荣刚等人当时就认识。

当时给我们上课的老师有不少带有江浙口音，我听得非常困难，口音重的我可以
说差不多听不懂。奇怪的是对黄老师口音很重的港普，我很快就没有语言障碍了。
黄老师本身年轻时有很多游历，香港成长，有留欧和留美经历，对近代欧洲文化
了如指掌，又有哲学背景。引经据典，讲起课来神采飞扬，很有魅力和个性。同
时他对学生又极为关心，特别能引导学生对数学的兴趣。我当时不是最好的学生，
但我的确深深得被他治学的态度和热情所吸引，也从讨论班这个过程扩大了眼界
和视野。还有一个重要原因，一度我在理科班有点迷失自我，突然碰到这么一位
有关注到你、甚至让你感觉到些许赏识的老师，你注定会感激他并且按他指引的
方向去走。可以说，黄老师是大学时期，对我影响最深的老师。到后来我坚持走
数学这条路，跟他一开始的启蒙和指引有不可分的关系。

黄老师的办公室在欧阳楼二楼，每次走进他的办公室他总是会先泡一杯速溶咖啡，
然后在狭窄的办公室内讨论数学和聊天话家常。这会让你觉得特别没有距离感，
他会给你各种学习、升学甚至是人生建议。黄老师打得非常好的兵乓球，年轻时
还在德国打过俱乐部。欧阳楼一楼就有乒乓球桌，我不记得是否跟他直接打过，
我记得跟孙晟昊经常打。浙大玉泉校区边上是青芝坞，离欧阳楼非常近，黄老师
跟我们经常讨论班后一起去那吃饭，吃饭时又能一阵海聊。那段时间我反而跟低
一级的同学走得更近，当时跟我们一起参加活动的还有黄老师的一个研究生，大
家相处地非常愉快。

黄老师非常鼓励学生出国学数学，我进了大学浑浑噩噩根本就没有这个想法甚至
没听说还有这个选项，等听说了这选项，已经大三大四太迟了，后来讨论班的学
弟学妹们出国的就很多了。我大学毕业后直博保送去了中科院，再后来又因为其
他机缘去了以色列留学。

每次回家我都会路过杭州看望一下黄老师，一方面跟他汇报自己的学习，另一方
面也是听 取他的意见。我印象特别深的是，我在博士毕业前申请博士后，他还
很细心地给我修改和润色申请材料，包括纠正很多英语语法错误。

在我看来，黄老师是非常纯粹的理想主义者，对自己追求的信念会以实际行动彻
底地去贯彻，不计较个人得失，甚至可能会得罪一些同事。他对名利非常淡薄，
为人有原则又有亲和力，对师生情谊异常看重，很多讨论班出来的学生都会跟他
保持联系和见面。去年夏天，在杭州跟沈烨峰一起跟黄老师见了一面，没想到那
竟是最后一面。一生中能遇到一个那么纯粹的人，在数学道路的关键点上对我产
生重要影响的老师，我心存感激，也会永远怀念。
