#+title: 记一个理想主义者 --- 心中永远的坐标 --- 黄兆镇
#+subtitle: The Most dedicated and influential math teacher in Zhejiang Univ.
#+OPTIONS: toc:nil ':t html-postamble:nil tags:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../minimal.css" />

转载自 [[https://wliumath.wordpress.com/2012/08/29/%E8%AE%B0%E4%B8%80%E4%B8%AA%E7%90%86%E6%83%B3%E4%B8%BB%E4%B9%89%E8%80%85-%E5%BF%83%E4%B8%AD%E6%B0%B8%E8%BF%9C%E7%9A%84%E5%9D%90%E6%A0%87-%E9%BB%84%E5%85%86%E9%95%87-the-most-dedicated-and-influentia/][流星小屋]].

我非老黄的学生，因为老黄的学生都是好学生，都是“黄派中人”，而我只是上过老黄的课和讨论班的蹭课的学生。但在ZJU的岁月中谁给我的影响最大？不是老杨也不是老李，而是老黄。

一直想写点关于老黄的文字，一直拖到今日。在年初看到\nbsp{}Facebook\nbsp{}中居然有老黄的专页，几个月后居然自己成为了专页的管理者，再一问老黄近况，发现老黄已经退休了，想来该写点东西了。

未见老黄真人前先闻大名，因为寝室中有人是“黄派中人”。因而去蹭老黄的“点拓”和“抽代”。

老黄的“点拓”是自编教材，免费送；老黄的“抽代”用的是\nbsp{}MIT\nbsp{}教材，机工引进版，原价59，老黄30一本给我们；不知道他是自己贴钱了还是如何，我想应该是自己贴了的吧。老黄的作业是很多的，是不允许迟交的，上课之前必须放到讲台上的，否则迟一分钟都是不收的。但是作业本子是老黄自己用钱买，课前下发活页纸每人10张。多不用退，少了自己去教超买。5人就是一包，每包5元，一次课他就得自掏作业本子钱至少\nbsp{}60\nbsp{}吧。而在浙大作为一个没科研的副教授，所有收入差不多在4万甚至不到4万一年的。 每次讨论班结束后，老黄请客聚餐一次，又是一笔。如此慷慨的老师，老黄算第一吧，我想这或许和老黄自己多年一直在校园求学有关，知道学生的拮据。然而，如今我虽同样站讲台，却做不到老黄的慷慨。

传闻老黄如此慷慨是因为老黄是富家子弟，家里再海德堡做和书相关的营生的。但这好像和老黄的慷慨没有必然逻辑。只知道老黄家在\nbsp{}ZJG\nbsp{}和\nbsp{}YQ\nbsp{}的中间点，每天背着双肩包，带着太阳镜，骑着自行车来上课，很是“潇洒”。好像老黄的家里也不大，生活条件并不好。

老黄对学生好是出名的，这不仅体现在对学生的体恤上，更是体现在对学生的严格上。

第一天上课，就听说老黄是不允许学生迟到的。上课铃响了，门就锁了，迟到的就不用进来了。上课是不允许学生碰手机等通讯设备和不允许学生说话和吃东西的。第一节课的时候他一上来就说：“我先说两件事。第一，我的粉笔字写的不好，普通话说的不好，你们可能看不懂也听不懂。第二，我这门课的挂课率很高，大约有60%。” 有一次一个同学叫陈海苗，迟到了5分钟被他批了一顿，老海一怒之下不去上课了。期中考试发卷子，老黄按成绩从高到低发，唯一一张100分的卷子没人取，就是老海的。然而老海终成为老黄门徒，跟了老黄五年，直到去了中科院数学所读博，今年毕业已经是北大讲师了。

老黄做事、教学乃至做人都很认真。我由于某些原因不能继续蹭课老黄的“抽代”就厚着脸皮向老黄要讲义复印，发现老黄的讲义是铅笔写的，修修补补很多，不是同样的讲义一用就是n年，老黄则是每年都重新整理补充的。

上老黄的讨论班很有挑战，不仅是作业多，更多的是要轮流上去报告，而老黄则孜孜不倦的在讨论班里各种“挑毛病”，非常细节的东西，包括你用的符号、术语、表述的方式等等。第一次听说巴尔巴基学派就是老黄这；第一次知道原来我从来都没有读对过希腊字母；第一次知道字母上一横读作 "bar"，尖帽读作 "hat"，波浪线读作 "tilta", 来自德语... 这些，我现在传承老黄教会我的这些给我的学生。但老黄能如此一遍一遍的不厌其烦地去帮别人纠正小错误，至少我觉得我自己是没法长期坚持的。他是一个很严格的人，无数次强调如果不好好准备的话，来讨论班其实是没有意义的。就像我现在告诉我的学生，可以不来上课，但是来上课就好好听讲一般。这些都是老黄教的。

老黄一个学期要开好几个讨论班，不仅给本科生开也给研究生开，排的满满的，双休都难有休息。在欧阳楼晚上自修到11点回寝室的时候还能经常碰到他才回家，大概还要至少骑半小时才能到家吧，大概快12点了吧。

补充个别人的段子：

#+BEGIN_QUOTE
我曾记得后来考试，他严得就没话说了，作弊几乎不可能，有个人考了59.5，但名捕总于挥动他那判官笔，批了个叉叉。后来直到大四的第一学期，才又有他给我们开得课《专业英语》。自然大家都认倒霉，粤语式的英语就更加动听了。他一开始就警告我们，我们可以不来上课， 也可以不做作业，但来上课的话，就不准迟到，不准讲空话，做作业的话就不准抄袭。可是这些话并不是所有人都听见了，我们前班长就不知道，他（杭州人）几乎长年把自己家当成浙大，所以有一天他去上课，已经迟到了，背着个包，摇摇晃晃，如同不倒翁。他直接从老师讲台穿过去，根本无视他的存在。黄老师就轻轻的说"stop, then out!”，我们老班长咂咂眼，习惯性的推一下快到鼻尖的眼镜，一听见说出去，就二话没说，很快的溜了出去，笑得我们雷声轰隆。班长毕竟是老大，我坐在那儿却很怕，因为我第一次来上这堂课。后来，他又说着不知那国洋文，说了一大通。然后把两位同学叫了起来，那两位可是我们班保研的大哥级人物。他说："you, you, pick up your bags, then out in five  minutes! and never in!"，也许我们都没听懂，他又用中文说了一遍，刹时，气氛一下子紧张，刚才轰鸣的笑声一下子留在记忆里了。原来他们互对作业，把欧几里德都翻译成欧拉了，说实在也只有他们两个认真做作业了。下课后，找了系主任还是没用，黄老师说除非开除他，他还是要这两个同学不及格。后来大家就一直做思想工作，可后来还是不及格。不过后来两位仁兄，一个保送清华，一个保送浙大。我记得黄老师曾经给我们说过， 香港是法制社会，所以他自己就天生如此了。这位曾经去过美国，德国，加拿大的学者， 最终选择浙大，也是天生的孽缘吧。
#+END_QUOTE

以自己职业来坚持道德准则的，也就是老黄了。老黄践行了老浙大的“求是”。而现今高校中考试监考不管，甚至老师帮助学生作弊都司空见惯，这不得不说是绝佳的讽刺，从高中到社会的这段过渡期——大学中就以行动告诉学生在中国特色社会上该如何行事。而更讽刺的是，做这类事情的大学教师往往都是辅导员或是本科留校的所谓学生会干部或是有关系的本校子弟。

老黄博学，通晓7国语言，唯一一个说不利索的就是普通话。子集读作“几值”，把极值读作“子集＂，我们读作“阿门”，我甚至听了半个学期后才明白他一直说的“温暖”原来是“紊乱or混乱”，着实让我“温暖”了半个学期。数学系也就老黄的普通话和李胜宏的湖南话折磨我了。

老黄的前30多年一直是在国外，据说干爷爷（干丹岩）93年去加拿大Alberta大学访问的时候碰到了老黄，不知咋的就把老黄给忽悠到了浙大。老黄30年后才踏上大陆土地，开学普通话。有同学考证老黄是和福建人学的，但是我个人存疑，因为在一次新生介绍会上，有学弟叫潘（轩宇？）是那次介绍会少数几个听懂老黄话的人，后来在介绍会上和老黄来来往往交流的不亦乐乎，当然，最后成为了老黄的得意弟子，一如既往的被老黄送到国外继续深造了。而潘是广东人，因此， 老黄说的应该是粤语普通话，老黄自己是香港人，学粤语普通话比学福建普通话要顺当的多。

不知道是因为老黄的普通话影响了交流，还是我们更加认为的老黄的桀骜不驯，更或是老黄作为香港人，根深蒂固的西方思维——直率，得罪人众多，可谓老景凄凉，系里面也就尹永成和卢涤明等少数几个谈的来。然而这种在中国社会所不被接受的直率，正是老黄的可贵之处。当今中国，最难说真话！ 而真挚的建议、批评能学生、朋友而言确实如此的珍贵。记得在西区的教师休息室内有一次向老黄请教关于我学习代数问题。老黄直言不讳的给我指出我的基础和情况不适合学基础数学，尤其是代数，比较适合搞计算机科学。还给我举了个例子，ZJU计算机学院的副院长陈越，ZJU ACM的荣誉缔造者，原来就是数学系的学生，留校后发现自己不适合继续搞数学，而去计算机学院发展了，如今已是硕果累累。事后证明，老黄是对的，尽管当时我不愿承认。

老黄的故事还有很多很多...老黄的传奇还在延续...

而老黄给我们植入的价值观是我们的内心力量，是坚持的源泉，明白自己的路在哪里，顺着自己的内心走下去。老黄虽然因为性格而境遇不如意，但毫无疑问，老黄的内心是强大的，是丰富的，因为很多学生回国第一站就是回到浙大看老黄，给老黄做报告。正如一个同学的留言“老黄把我带进了数学的门，还把我送出了国，如今我却因数学越学越半吊子而不敢回去看他。老黄虽非我父，我却觉得自己很不孝。”

老黄在我心中就是个坐标，淡泊名利，认真做事、做人，跟随自己的内心...

“老黄我们爱你！” 今天是您的生日，祝您生日快乐！永远健康，支撑我们的内心！
