#+title: 黄老师和他的讨论班
#+OPTIONS: toc:nil ':t html-postamble:nil tags:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../minimal.css" />

文／夏颉

05年9月，杭州酷暑，我拖着行李走进紫金港。

作为懵懂的新生，我急于联系浙大的高中学长讨求经验，于是我见到了高我一届的闫嘉平学长。在蓝田一舍的大厅，闫嘉平略带激动地讲述他的同学潘宣余数学多么好。我清楚地记得，闫学长列举的事例包括"潘宣余大一还没结束就选定黄兆镇做导师了！"

满眼星星的我忙着点头，心里掠过一个问题:"黄兆镇老师是谁？选他做导师怎么个牛法？" 不过，闫学长没给我提问的机会，但黄老师已经给我留下了神一般的形象。

第一次见到黄老师，是在几个月后，他给竺院开设的导论课上。身材瘦小，一口港普，不怒自威，亲而难犯。 这个第一印象，让我在以后四年里，每次见到黄老师都有些许紧张。

导论课中的学生，大都来自理科班。随着课程推进，人数下降很快。不过黄老师丝毫不在意，“人贵精而不贵多”。坚持到最后的几个人，都和黄老师熟络了。这些人，日后在诸多讨论班中相伴彼此，一起学(bei)习(nve)。

大一和大二之间的暑假，我们正式进入了黄老师的讨论班训练体系。近八周的时间，我们在玉泉的一间小教室里学习\nbsp{}Rudin\nbsp{}的《数学分析原理》，带我们的是王丽涵学姐。一起学习的包括但不限于: 陈立玮，刘宇杰和马英举。

我记得，讨论班是在晚上，隔天一讨论。没有讨论班的时候，我就在紫金港空调自习室里啃习题; 有讨论班的那些天，我趁着凉快，一早就骑车奔去玉泉，找个凉快的教室看书或眯着（那时玉泉里有空调的教室很少，很快就人满为患），等到晚上讨论班结束了，趁着有一丝晚风再骑回紫金港。那一个多月的生活真是简单而惬意。

我记得，马英举的报告风格得到大家一致好评，从他的报告中，我学到了很多数学，也对好的报告有了初步的感觉。不过后来，他的兴趣转向了经济学，（他在\nbsp{}CCER\nbsp{}读研后又去了\nbsp{}UCLA\nbsp{}读经济学博士），我就没机会再向他学习。

我记得，当时有三个讨论班并行，王丽涵学姐监督我们的同时，还参与了另一个"高级"讨论班的学习，颇为疲惫，时常抱怨脖子疼。她颈椎的问题，一直伴随她到博士毕业。

大二开始后，选修了黄老师的点集拓扑，同时开始讨论拓扑学和抽象代数。当时颇冒进，还旁听了黄老师给大三学生开的抽代 II。黄老师可能感动于我的积极，答应做我的导师。那一年，脑子装了很多数学知识，但很多只流于表面，真正理解的并不多。这个病灶一年后终于爆发。

那一年，从潘宣余学长那听了不少黄老师的轶事。印象最深的之一，是黄老师成长于香港，家境殷实，但和怹父亲关系并不算好。成年后，黄老师孤身去美国和德国求学，生活颇为困难。怹父亲寄了张支票，结果怹把支票撕碎后又寄回香港。在德国读本科时的费用都是怹自己打工挣来的，也因此耽误了时间，导致本科学位近七年才拿下。（后来我到了德国才知道，在德国读本科延毕是很普遍的，多数因为课程太难。）

大三上学期我在香港交流，那是黄老师的故乡。记得我交流结束刚回到浙大，黄老师就笑着问我，粤语学会了几句。我很惭愧，就会了一句"谢谢"。

那时我还延续着冒进的风格，自以为在香港自学了代数拓扑，想直接参加黄老师代拓的期末考试。结果很惨。大三下，刚开学，我就在黄老师的课后被怹叫住，当着周围同学的面被骂。那次批评中，怹的经典句式：”你完全没懂！”算程度最轻的。怹表示，现在这个样子，我就别想出国读博了。

那一次，周围的同学都觉得骂得有些重，好在我没皮没脸惯了，倒坦然接受。褒贬是买主，肯骂我的人，大都是为我好，对我还抱有希望。黄老师教授知识无私负责，指出问题也直切要害。

知耻而后勇，我继续按着黄老师的安排学习，同时慢慢地查漏补缺。这样进入了大四，GRE，申请，等结果的同时，讨论班的进度也没落下。

来到哥大后，第一次助教，用的教材就是\nbsp{}Rudin\nbsp{}的《数学分析原理》，恍如隔世。

我进入哥大不久，黄老师就面临退休，那时，我们这些曾受益于他的学生，都担心他的讨论班体系无法维系。高我两届的朱一学长挺身而出，组织我们捐款，写信，帮黄老师争取一些权益。那签着\nbsp{}70\nbsp{}多个名字和所在学校的联名信，就是在朱一学长的联络和组织下才成形。

在哥大的这五年里，我见识了不少数学界真正神一样的人物。黄老师的数学水平，和这些人的差距不以里计。但黄老师对我，对浙大学数学的学生的影响，远远大过那些传奇。不仅在于怹对本科数学教学的创新和尝试，而且在于怹深厚的个人魅力和散发的理想主义光辉。

近几年里，浙大出国读基础数学的学生，大都出于黄老师门下。怹带出的学生中，也不乏在\nbsp{}Google\nbsp{}和高盛这些行业内顶级公司工作的人，但怹最为之自豪的，是"已有30多人拿到博士学位，20多人做博士后，7人是副教授。如果说10年以后，他们中会有30位教授，这应该不是过高的期望"。我觉得30位教授还是保守估计，但百感交集的是，自己无法成为这\nbsp{}10\nbsp{}年后的\nbsp{}1/30\nbsp{}了。

浙江大学\nbsp{}118\nbsp{}岁生日刚过去，闫嘉平学长的九年祭也不远了，我在伦敦即将开始新的人生旅程。特殊的时刻，看到了一篇黄老师的访谈。往昔时光，那些人，那些事，那些触动，再次浮现。谨以这些文字，寥表纪念。
