#+title: 纪念黄老师
#+OPTIONS: toc:nil ':t html-postamble:nil tags:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../minimal.css" />

文／杨毅

我也想写点什么来着纪念这位可敬可爱的老师了，虽然他几乎不太可能认识我。黄老师的点集拓扑课我的确是印象深刻，因为那是我第一次考不及格的课，很惭愧，那时对于那些抽象的开集闭集连续聚点的概念我完全无法适应，如同天书一样，然而后来才知道那些都是最基础的概念，也是最精华的总结，数学总是那么凝炼而又精确。

再次接触到这些概念是工作以后了，通过一个叫做shapely的处理平面几何物体的库体会到了这些概念的威力，工作中遇到的平面几何对象可以很方便地用这个库处理，而因为点集拓扑的存在我可以很轻易地理解contains和covers方法的差异，不会用错，也可以理解九交模型是怎么回事，这些都是点集拓扑里最基础的，我也体会到了数学抽象的美。

上学那个时候互联网还不发达，上课的内容如果没听懂是很难再补回来的，也可以说自己的学习方法不对，并不是天生的不愿努力。然而当再次遇到它们的时候，一切又是感觉那么亲切和熟悉。数学是非常需要思考的学问，数学里的定理，别管它有多么复杂，无数次在给我们演示着同样一件事：把复杂的问题变成若干简单问题的组合，把未知化为已知，然后用已知的方法解决问题，在这个过程中，新的方法产生了，这不正是我们解决现实问题的方法吗？所以现在做数学应用的相关问题的时候，我从来不嫌弃使用的方法过于简单，简单的加减乘除有的时候就能发挥巨大的作用，而不一定非要引入高大上的积分和求导。

数学又以其强大的确定性指引着我们，当面对一个悬而未决的问题是，普通人会直接去想解决办法，可能会想很久，然后以失败告终，而数学人总是会先问一下，这个问题的解存在吗？对于一个特定的问题，数学可能会告诉你：老兄啊，这个问题的解是不存在的，别费那个劲了。数学说存在就是存在，不存在就是不存在，它就是这么自信而且正确！于是你很快排除了一些不需要探索的道路，只在那些可能有解的问题上深入探索，最终得到的结果又快又好。

工作之余，再看看数学也是快乐的事情，当年没弄明白的多看几遍也能明白个七七八八，甚至产生新的认识。我觉得数学就像是武侠小说里的九阴真经，练好了你就是绝顶高手，练不好也没什么危害，你练不练它都在那里，但它的大门永远向你敞开的，从这个角度说，数学又是无私的。

如果回到学校，黄老师再问我一次：你喜欢数学吗？我会说：喜欢。如果黄老师再追问：你愿意研究数学吗？我会笑笑说：还是算了吧，不是那块料。我与数学的缘分大概就是站在门口一窥它的美丽和奥妙，从中拿走一些果实来优化自己的生活，再膜拜一下那些能在数学领域如鱼得水的大神们，仅此而已吧。
